#+TITLE: On a seam
#+DATE: <2025-02-10>

I find myself exiting a subway train, my father is there with me.

I walk up the stairs of the station, between layered halls of glass
reflecting a brutalist, grey masonry reminiscent of calculated
machinery. I assume the architect means to impart the experience of
being inside an engine gearbox. People flood the station concourse
like oil over meshed cogs, uniformly wiped in their dark business attire.

Coming out through the shaft, to the exit, the early evening sky is an
odd haze of purplish smog. A cool breeze pushes the passers by along
the sidewalk. Something feels familiar about this place, it's
somewhere I've been before, albeit unsettling.

My father looks to the tall buildings in the distance, but is cut off
by a man walking past. The man seems to exist in two places at once,
he loses a step but continues as if nothing happened. I remark "the
people here are all on their own journies", to which my father says,
"is this where you want to go?"
