#+TITLE: John's site
#+OPTIONS: title:nil

#+BEGIN_EXPORT html
<h2 title="I dont know nothing about no calculus.">
<code>(limit (perception iota) iota -&gt; truth)</code>
</h2>
#+END_EXPORT

[[https://patreon.com/cc_jsullivan][Support me on Patreon]]

[[./resume.pdf][Resume]]
[[./portfolio.org][Portfolio]]
[[#contact][Contact]]
[[https://github.com/jjsullivan5196][Github]]
[[https://linkedin.com/in/jjsullivan5196][LinkedIn]]
[[https://instagram.com/cc.jsullivan][Instagram]]

* A place for friends
Hi, I'm John, and this is my website.

This will be the record of my
[[https://en.wikipedia.org/wiki/Sabbatical][sabbatical]], hopefully
concluding in some approximation of
[[https://en.wikipedia.org/wiki/Truth][what is]], or a permanent
working holiday in Tokyo.

Please see my [[#contact][contact]] for business inquiries.

* Articles & writing


