#+TITLE: John's site
#+OPTIONS: title:nil

#+BEGIN_EXPORT html
<h2 title="foo">
<pre>(apply reason)</pre>
</h2>
#+END_EXPORT

[[https://patreon.com/cc_jsullivan][Support me on Patreon]]

[[./resume.pdf][Resume]]
[[./portfolio.org][Portfolio]]
[[#contact][Contact]]
[[/rss.xml][RSS]]
[[https://github.com/jjsullivan5196][Github]]
[[https://linkedin.com/in/jjsullivan5196][LinkedIn]]
[[https://instagram.com/cc.jsullivan][Instagram]]

* A place for friends
Hi, I'm John, and this is my website.

Please see my [[#contact][contact]] for business inquiries.

* Articles & writing
